[package]
name = "libp2p-bitswap"
version = "0.4.1"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
description = "Implementation of the ipfs bitswap protocol."
license = "MIT OR Apache-2.0"
repository = "https://github.com/ipfs-rust/libp2p-bitswap"

[build-dependencies]
prost-build = "0.6.1"

[dependencies]
async-std = { version = "1.5.0", features = ["attributes"] }
fnv = "1.0.7"
futures = "0.3.5"
libipld-core = "0.3.0"
libp2p-core = "0.20.0"
libp2p-swarm = "0.20.0"
log = "0.4.8"
prost = "0.6.1"
thiserror = "1.0.19"
unsigned-varint = "0.3.3"

[dev-dependencies]
env_logger = "0.7.1"
libp2p = "0.19.0"
